### ISSUE TITLE
Smack21 and Highfive21

### ISSUE THREAD

**Issue by pranavgoel29** [clarkio/ttv-chat-bot#114]
We can have a !command like smack21 and it will start smack for 21 times and we can do same with highfive21 and you can add that smack voice (stream)

After writing the command there will be a series of 21 smacks or 21 highfives this could be so fun

**Comment by clarkio** [comment]
Haha I'm not sure about having it run the animation that many times but I'll keep it in mind. I think for now I'd prefer to keep it running once per command entry in chat. Thanks for sharing this funny idea though!

**Comment by pranavgoel29** [comment]
> Haha I'm not sure about having it run the animation that many times but I'll keep it in mind. I think for now I'd prefer to keep it running once per command entry in chat. Thanks for sharing this funny idea though!

Haha, no worries understandable as it will be a really long one 😅😂
