### ISSUE TITLE
TS7053 Error when running npm start

### ISSUE THREAD

**Issue by wwsean08** [clarkio/ttv-chat-bot#115]
### This issue is for a: (mark with an `x`)

- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
1. Checkout the current master (rev b716ba4 as of right now)
2. Follow the getting started instructions (I will admit I skipped the stream elements config portion but I am getting a code error from compilation so it shouldn't matter)
3. Run `npm start` and see that it errors out.

### Any log messages given by the failure

> compiling client...
> 
> ttv-chat-light@0.1.0 compile-server /root/ttv-chat-light
> echo compiling server... & tsc -p ./src/server
> 
> compiling server...
> src/server/obs-manager.ts:258:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'typeof EffectType'.
> 
> 258         EffectType[sceneEffectSetting.effectType] || EffectType.None;
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 1 error.
> 
> 
> npm ERR! Linux 4.15.0-66-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile-server"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! ttv-chat-light@0.1.0 compile-server: `echo compiling server... & tsc -p ./src/server`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the ttv-chat-light@0.1.0 compile-server script 'echo compiling server... & tsc -p ./src/server'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ttv-chat-light package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     echo compiling server... & tsc -p ./src/server
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ttv-chat-light
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ttv-chat-light
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/ttv-chat-light/npm-debug.log
> 

### Expected/desired behavior
The code compiles and starts running

### OS and Version?
Ubuntu 18.04.3 (fresh VM spun up on DigitalOcean to test and verify it wasn't an environmental issue on my machine)

### Versions
Commit sha b716ba475446578921e1fa6742f5021e6e26e457 (current master commit as of the time I am writing this)

### Mention any other details that might be useful
This was run into on stream yesterday as well I believe.

**Comment by clarkio** [comment]
Hey thanks for reporting this. I think it's since been addressed so closing for now but if you run into it again let me know and just reference this issue.
