### ISSUE TITLE
countdown Effect idea for highfive and smacks

### ISSUE THREAD

**Issue by pranavgoel29** [clarkio/ttv-chat-bot#128]
We can add a sound effect before the highfive or smack sfx being played 
*We can add simple countdowns like 12345 or
as roberttabbles suggested we can add "TACTICAL HIGH FIVE INCOMING!"

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clarkio** [comment]
We've added this now and thanks for the idea @pranavgoel29 !

**Comment by pranavgoel29** [comment]
> We've added this now and thanks for the idea @pranavgoel29 !

Thank you 😃
