### ISSUE TITLE
OBS Websocket Connection Retry Logic

### ISSUE THREAD

**Issue by clarkio** [clarkio/ttv-chat-bot#141]
Need to have the chatbot attempt to connect to the OBS Websockets server on startup and if it fails retry x number of times and if all tries fail THEN give up. Bring it Chair Kappa

**Comment by 1TekPro** [comment]
If you want to change the color of an overlay, should the websocket be set for streamelements, obs or both?

**Comment by clarkio** [comment]
@1TekPro very sorry for the delay in responding! Did you happen to sort it out or how did things go?

The overlay color changes need to happen in the locally hosted views. Those views have a socket.io client to connect to the socket.io server that's created in the server of the bot ([seen here](https://github.com/clarkio/ttv-chat-bot/blob/main/src/server/server.ts#L47-L48)).

Then when the !bulb (or whatever command name you're using) is triggered it will tell the socket.io server to emit the color change to the client: https://github.com/clarkio/ttv-chat-bot/blob/main/src/server/overlay.ts#L30-L32

Once that event is emitted from the server the client listening for events will receive it and take action on it: https://github.com/clarkio/ttv-chat-bot/blob/main/src/client/stream.ts#L26-L29

Hope this helps and thanks for your interest in the project!

**Comment by clarkio** [comment]
This issue has been implemented now so closing.

@1TekPro if you'd like to discuss your question more please open a separate issue and I'll be happy to continue the conversation there 🙂👍
